#! /bin/bash

cd data/

	#gnuplot plot1-1.gnu >> output.txt

	#gnuplot plot1-3.gnu >> output.txt

	gnuplot plot2-1.gnu >> output.txt


	rm output.txt

cd ..

cd tables/

	 #./table-maker ./../data/1-1.dat 1-1-tabela.tex

	 #./table-maker ./../data/1-2.dat 1-2-tabela.tex

	 #./table-maker ./../data/1-3.dat 1-3-tabela.tex

	 #./table-maker ./../data/2-1.dat 2-1-tabela.tex

cd ..

	pdflatex -shell-escape exp3.tex >> output.txt

	rm output.txt

	#gnome-open exp3.pdf 
