#! /bin/bash

#gcc quest2.c -o quest2 -lm
#./quest2

#gcc quest3.c -o quest3 -lm
#./quest3

gcc quest4.c -o quest4 -lm
./quest4

#gcc quest6.c -o quest6 -lm
#./quest6

#gcc quest6-2.c -o quest6-2 -lm
#./quest6-2

#gcc quest8.c -o quest8 -lm
#./quest8

#gcc quest8-2.c -o quest8-2 -lm
#./quest8-2

#gcc quest9-1.c -o quest9-1 -lm
#./quest9-1

#gcc quest9-2.c -o quest9-2 -lm
#./quest9-2

#gcc quest10.c -o quest10 -lm
#./quest10


cd data/


#gnuplot plot2-1.gnu

#gnuplot plot3-1.gnu

#gnuplot plot4-1.gnu

gnuplot plot6-1.gnu

#gnuplot plot6-2.gnu

#gnuplot plot8-1.gnu

#gnuplot plot9-1.gnu

gnuplot plot10-1.gnu
cd ..

pdflatex relatorio.tex >> rurex

rm rurex

gnome-open relatorio.pdf


